// Generated by build.mjs; edit src/ instead.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/api.ts
var api_exports = {};
__export(api_exports, {
  requestApi: () => requestApi
});
async function requestApi(transport, base, token, path, method = "GET", body) {
  let url;
  try {
    url = new URL(base.trim());
  } catch {
    throw new Error("Configure a valid NAS API URL in plugin settings.");
  }
  if (!["http:", "https:"].includes(url.protocol) || url.username || url.password || url.search || url.hash) {
    throw new Error("Use an HTTP or HTTPS API URL without credentials, query, or fragment.");
  }
  if (!path.startsWith("/v1/") || path.includes("..")) throw new Error("Invalid API path.");
  if (!token) throw new Error("Connect this device to NAS first.");
  const headers = { Accept: "application/json", Authorization: `Bearer ${token}` };
  if (body !== void 0) headers["Content-Type"] = "application/json";
  let response;
  try {
    response = await transport({
      url: base.trim().replace(/\/$/, "") + path,
      method,
      headers,
      body: body === void 0 ? void 0 : JSON.stringify(body),
      throw: false
    });
  } catch {
    throw new Error("Cannot reach the NAS API. Check the private connection and server address.");
  }
  if (response.status === 401 || response.status === 403) throw new Error("NAS access denied. Check this device's authorization.");
  if (response.status === 409 || response.status === 412) throw new Error("The server copy changed. Refresh before editing again.");
  if (response.status < 200 || response.status >= 300) throw new Error(`NAS request failed (HTTP ${response.status}).`);
  let data;
  try {
    data = JSON.parse(response.text);
  } catch {
    throw new Error("NAS returned an invalid JSON response.");
  }
  if (!data || data.apiVersion !== 1) throw new Error("NAS API version is incompatible with this plugin.");
  return data;
}
var init_api = __esm({
  "src/api.ts"() {
  }
});

// src/sync-api.ts
var sync_api_exports = {};
__export(sync_api_exports, {
  commitUpload: () => commitUpload,
  exportAccount: () => exportAccount,
  history: () => history,
  importAccount: () => importAccount,
  manifest: () => manifest,
  pathUrl: () => pathUrl,
  renameRemote: () => renameRemote,
  restoreRevision: () => restoreRevision,
  revisionContent: () => revisionContent,
  startUpload: () => startUpload,
  syncRequest: () => syncRequest,
  trash: () => trash,
  uploadChunk: () => uploadChunk,
  uploadStatus: () => uploadStatus
});
function pathUrl(path) {
  return "/sync/v1/files/" + path.split("/").map(encodeURIComponent).join("/");
}
async function syncRequest(transport, base, token, path, method = "GET", body, condition = {}, contentType = "application/octet-stream") {
  if (!token) throw new Error("Connect this device to NAS first.");
  const url = new URL(base.trim());
  if (!/^https?:$/.test(url.protocol) || url.username || url.password || url.search || url.hash) throw new Error("Configure a valid private vault-sync API URL.");
  if (!path.startsWith("/sync/v1/") || path.includes("..")) throw new Error("Invalid vault-sync API path.");
  const headers = { Authorization: `Bearer ${token}`, Accept: "application/json", ...condition };
  if (body !== void 0) headers["Content-Type"] = contentType;
  let response;
  try {
    response = await transport({ url: base.replace(/\/$/, "") + path, method, headers, body, throw: false });
  } catch {
    throw new Error("Cannot reach the private vault-sync service.");
  }
  if (response.status === 401 || response.status === 403) throw new Error("Vault sync access denied.");
  if (response.status === 409 || response.status === 412) throw new Error("Vault changed remotely; preserve a conflict and refresh.");
  if (response.status < 200 || response.status >= 300) throw new Error(`Vault sync failed (HTTP ${response.status}).`);
  return response;
}
async function manifest(transport, base, token) {
  const r = await syncRequest(transport, base, token, "/sync/v1/manifest");
  const data = JSON.parse(r.text);
  if (!data || data.apiVersion !== 1 || !Array.isArray(data.entries)) throw new Error("Vault sync API version is incompatible.");
  return data;
}
function uploadSession(response) {
  let value;
  try {
    value = JSON.parse(response.text);
  } catch {
    throw new Error("Vault sync API returned an invalid upload response.");
  }
  if (!value || value.apiVersion !== 1 || typeof value.uploadId !== "string" || !Number.isInteger(value.offset) || !Number.isInteger(value.size) || !Number.isInteger(value.chunkSize) || value.offset < 0 || value.offset > value.size || value.chunkSize < 1) throw new Error("Vault sync API returned an incompatible upload response.");
  return value;
}
async function startUpload(transport, base, token, value) {
  return uploadSession(await syncRequest(transport, base, token, "/sync/v1/uploads", "POST", JSON.stringify(value), {}, "application/json"));
}
async function uploadStatus(transport, base, token, uploadId) {
  return uploadSession(await syncRequest(transport, base, token, `/sync/v1/uploads/${encodeURIComponent(uploadId)}`));
}
async function uploadChunk(transport, base, token, uploadId, offset, bytes) {
  return uploadSession(await syncRequest(transport, base, token, `/sync/v1/uploads/${encodeURIComponent(uploadId)}`, "PUT", bytes, { "X-Upload-Offset": String(offset) }));
}
async function commitUpload(transport, base, token, uploadId) {
  await syncRequest(transport, base, token, `/sync/v1/uploads/${encodeURIComponent(uploadId)}/commit`, "POST");
}
async function history(transport, base, token, path) {
  const suffix = path ? `?path=${encodeURIComponent(path)}` : "";
  const value = JSON.parse((await syncRequest(transport, base, token, `/sync/v1/history${suffix}`)).text);
  return Array.isArray(value.entries) ? value.entries : [];
}
async function trash(transport, base, token) {
  const value = JSON.parse((await syncRequest(transport, base, token, "/sync/v1/trash")).text);
  return Array.isArray(value.entries) ? value.entries : [];
}
async function revisionContent(transport, base, token, revision) {
  const response = await syncRequest(transport, base, token, `/sync/v1/revisions/${encodeURIComponent(revision)}`);
  if (!response.arrayBuffer) throw new Error("Revision content was unavailable.");
  return response.arrayBuffer;
}
async function restoreRevision(transport, base, token, revision) {
  return JSON.parse((await syncRequest(transport, base, token, "/sync/v1/trash/restore", "POST", JSON.stringify({ revision }), {}, "application/json")).text);
}
async function renameRemote(transport, base, token, path, newPath, ifMatch, ifRevision) {
  const body = { path, newPath, ...ifMatch ? { ifMatch } : {}, ...ifRevision ? { ifRevision } : {} };
  return JSON.parse((await syncRequest(transport, base, token, "/sync/v1/files/rename", "POST", JSON.stringify(body), {}, "application/json")).text);
}
async function exportAccount(transport, base, token) {
  const response = await syncRequest(transport, base, token, "/sync/v1/account/export");
  if (!response.arrayBuffer) throw new Error("Account export was unavailable.");
  return response.arrayBuffer;
}
async function importAccount(transport, base, token, archive, dryRun = false) {
  const suffix = dryRun ? "?dryRun=1" : "";
  const response = await syncRequest(transport, base, token, `/sync/v1/account/import${suffix}`, "POST", archive, {}, "application/zip");
  return JSON.parse(response.text);
}
var init_sync_api = __esm({
  "src/sync-api.ts"() {
  }
});

// src/scope.ts
var scope_exports = {};
__export(scope_exports, {
  classifyVaultPath: () => classifyVaultPath,
  scopeSummary: () => scopeSummary
});
function classifyVaultPath(path) {
  if (!isSafeRelativePath(path)) {
    return { scope: "user-reviewed", reason: "The path is not a safe vault-relative path." };
  }
  if (DEVICE_LOCAL_PATHS.has(path) || DEVICE_LOCAL_PREFIXES.some((prefix) => path.startsWith(prefix))) {
    return { scope: "device-local", reason: "Obsidian workspace, cache, appearance, or trash state is device-local." };
  }
  if (path === ".obsidian" || path.startsWith(".obsidian/")) {
    return { scope: "user-reviewed", reason: "Obsidian configuration and plugin resources require an explicit compatibility review." };
  }
  if (path === ".git" || path.startsWith(".git/")) {
    return { scope: "user-reviewed", reason: "Git metadata must not be handled by a vault synchronization protocol." };
  }
  if (path.includes(".conflict-")) {
    return { scope: "user-reviewed", reason: "Conflict copies stay on the affected device until reviewed." };
  }
  return { scope: "shared", reason: "User content is eligible for the future shared-content policy." };
}
function scopeSummary() {
  return [
    "Shared: Markdown and attachments outside protected application-state folders.",
    "Device-local: workspace, cache, appearance, hotkey, and trash state.",
    "User-reviewed: .obsidian plugin/configuration resources and Git metadata."
  ];
}
function isSafeRelativePath(path) {
  return Boolean(path) && !path.startsWith("/") && !path.includes("\\") && !path.split("/").some((segment) => !segment || segment === "." || segment === "..");
}
var DEVICE_LOCAL_PATHS, DEVICE_LOCAL_PREFIXES;
var init_scope = __esm({
  "src/scope.ts"() {
    DEVICE_LOCAL_PATHS = /* @__PURE__ */ new Set([
      ".obsidian/app.json",
      ".obsidian/appearance.json",
      ".obsidian/hotkeys.json",
      ".obsidian/workspace.json",
      ".obsidian/workspace-mobile.json"
    ]);
    DEVICE_LOCAL_PREFIXES = [
      ".obsidian/cache/",
      ".obsidian/workspace/",
      ".trash/"
    ];
  }
});

// src/sync-plan.ts
var sync_plan_exports = {};
__export(sync_plan_exports, {
  conflictPath: () => conflictPath,
  resolveChange: () => resolveChange,
  sourcePathForConflictCopy: () => sourcePathForConflictCopy
});
function resolveChange(local, remote) {
  if (local === "unchanged" && remote === "unchanged") return "none";
  if (local === "unchanged") return "download";
  if (remote === "unchanged") return "upload";
  return "conflict";
}
function conflictPath(path, device, timestamp) {
  const name = device.replace(/[^a-z0-9-]/gi, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "device";
  const time = timestamp.replace(/[^0-9TZ-]/g, "");
  const dot = path.lastIndexOf(".");
  return dot > 0 ? `${path.slice(0, dot)}.conflict-${name}-${time}${path.slice(dot)}` : `${path}.conflict-${name}-${time}`;
}
function sourcePathForConflictCopy(path) {
  const match = /^(.*)\.conflict-[a-z0-9-]+-\d{4}-\d{2}-\d{2}T\d{6,}Z(\.[^/]+)?$/i.exec(path);
  return match ? `${match[1]}${match[2] || ""}` : void 0;
}
var init_sync_plan = __esm({
  "src/sync-plan.ts"() {
  }
});

// src/sync-reconcile.ts
var sync_reconcile_exports = {};
__export(sync_reconcile_exports, {
  reconcile: () => reconcile
});
function different(left, right) {
  return (left?.sha256 || "") !== (right?.sha256 || "");
}
function reconcile(base, local, remote) {
  const baseByPath = new Map(base.map((item) => [item.path, item]));
  const localByPath = new Map(local.map((item) => [item.path, item]));
  const remoteByPath = new Map(remote.map((item) => [item.path, item]));
  const paths = /* @__PURE__ */ new Set([...baseByPath.keys(), ...localByPath.keys(), ...remoteByPath.keys()]);
  return [...paths].sort().map((path) => {
    const previous = baseByPath.get(path), here = localByPath.get(path), there = remoteByPath.get(path);
    const localChanged = different(previous, here), remoteChanged = different(previous, there);
    if (!localChanged && !remoteChanged) return { kind: "none", path, base: previous, local: here, remote: there };
    if (!localChanged) return { kind: there ? "download" : "delete-local", path, base: previous, local: here, remote: there };
    if (!remoteChanged) return { kind: here ? "upload" : "delete-remote", path, base: previous, local: here, remote: there };
    return { kind: "conflict", path, base: previous, local: here, remote: there };
  });
}
var init_sync_reconcile = __esm({
  "src/sync-reconcile.ts"() {
  }
});

// src/sync-state.ts
var sync_state_exports = {};
__export(sync_state_exports, {
  clearPendingUpload: () => clearPendingUpload,
  clearSyncState: () => clearSyncState,
  loadPendingUpload: () => loadPendingUpload,
  loadSyncIssues: () => loadSyncIssues,
  loadSyncState: () => loadSyncState,
  markIssueReviewed: () => markIssueReviewed,
  markSetupCopyRecovered: () => markSetupCopyRecovered,
  recordSyncFailure: () => recordSyncFailure,
  recordSyncResult: () => recordSyncResult,
  savePendingUpload: () => savePendingUpload,
  saveSyncIssues: () => saveSyncIssues,
  saveSyncState: () => saveSyncState
});
function scoped(key, scope = "default") {
  return `${key}.${scope}`;
}
function loadSyncState(scope) {
  try {
    const raw = window.localStorage.getItem(scoped(KEY, scope));
    return raw ? JSON.parse(raw) : void 0;
  } catch {
    return void 0;
  }
}
function saveSyncState(entries, revision, scope) {
  window.localStorage.setItem(scoped(KEY, scope), JSON.stringify({ entries, revision, updatedAt: (/* @__PURE__ */ new Date()).toISOString() }));
}
function clearSyncState(scope) {
  try {
    window.localStorage.removeItem(scoped(KEY, scope));
  } catch {
  }
}
function pendingUploads(scope) {
  try {
    const value = JSON.parse(window.localStorage.getItem(scoped(PENDING_UPLOADS_KEY, scope)) || "{}");
    return value && typeof value === "object" && !Array.isArray(value) ? value : {};
  } catch {
    return {};
  }
}
function loadPendingUpload(path, scope) {
  const value = pendingUploads(scope)[path];
  return value && typeof value.uploadId === "string" && typeof value.sha256 === "string" && Number.isInteger(value.size) ? value : void 0;
}
function savePendingUpload(value, scope) {
  const uploads = pendingUploads(scope);
  uploads[value.path] = value;
  window.localStorage.setItem(scoped(PENDING_UPLOADS_KEY, scope), JSON.stringify(uploads));
}
function clearPendingUpload(path, scope) {
  const uploads = pendingUploads(scope);
  delete uploads[path];
  try {
    window.localStorage.setItem(scoped(PENDING_UPLOADS_KEY, scope), JSON.stringify(uploads));
  } catch {
  }
}
function loadSyncIssues(scope) {
  try {
    const value = JSON.parse(window.localStorage.getItem(scoped(ISSUES_KEY, scope)) || "[]");
    return Array.isArray(value) ? value.filter((item) => item && typeof item.id === "string" && typeof item.kind === "string") : [];
  } catch {
    return [];
  }
}
function saveSyncIssues(value, scope) {
  try {
    window.localStorage.setItem(scoped(ISSUES_KEY, scope), JSON.stringify(value.slice(-100)));
  } catch {
  }
}
function recordSyncResult(result, scope) {
  const issues = loadSyncIssues(scope);
  const details = result.conflictDetails || [];
  for (const path of result.conflictPaths || []) {
    const detail = details.find((item) => item.conflictPath === path || item.path === path);
    issues.push({ id: `${Date.now()}-${path}`, kind: "conflict", path: detail?.path || path, conflictPath: path, base: detail?.base, local: detail?.local, remote: detail?.remote, detail: "Both copies changed; the local copy was preserved as a conflict file.", createdAt: (/* @__PURE__ */ new Date()).toISOString() });
  }
  saveSyncIssues(issues, scope);
}
function recordSyncFailure(error, scope) {
  const detail = error instanceof Error ? error.message : "Vault synchronization could not complete.";
  const issues = loadSyncIssues(scope);
  issues.push({ id: `${Date.now()}-failure`, kind: "sync-failed", detail, createdAt: (/* @__PURE__ */ new Date()).toISOString() });
  saveSyncIssues(issues, scope);
}
function markIssueReviewed(id, scope) {
  saveSyncIssues(loadSyncIssues(scope).map((item) => item.id === id ? { ...item, reviewed: true } : item), scope);
}
function markSetupCopyRecovered(path, scope) {
  saveSyncIssues(loadSyncIssues(scope).map((item) => item.kind === "conflict" && item.path === path ? { ...item, reviewed: true } : item), scope);
}
var KEY, PENDING_UPLOADS_KEY, ISSUES_KEY;
var init_sync_state = __esm({
  "src/sync-state.ts"() {
    KEY = "nas-vault-sync.v1.base";
    PENDING_UPLOADS_KEY = "nas-vault-sync.v1.pending-uploads";
    ISSUES_KEY = "nas-vault-sync.v1.issues";
  }
});

// src/sync-engine.js
var require_sync_engine = __commonJS({
  "src/sync-engine.js"(exports2, module2) {
    var { requestUrl } = require("obsidian");
    var { manifest: manifest2, pathUrl: pathUrl2, syncRequest: syncRequest2, startUpload: startUpload2, uploadStatus: uploadStatus2, uploadChunk: uploadChunk2, commitUpload: commitUpload2, renameRemote: renameRemote2 } = (init_sync_api(), __toCommonJS(sync_api_exports));
    var { classifyVaultPath: classifyVaultPath2 } = (init_scope(), __toCommonJS(scope_exports));
    var { conflictPath: conflictPath2, sourcePathForConflictCopy: sourcePathForConflictCopy2 } = (init_sync_plan(), __toCommonJS(sync_plan_exports));
    var { reconcile: reconcile2 } = (init_sync_reconcile(), __toCommonJS(sync_reconcile_exports));
    var { loadSyncState: loadSyncState2, saveSyncState: saveSyncState2, loadPendingUpload: loadPendingUpload2, savePendingUpload: savePendingUpload2, clearPendingUpload: clearPendingUpload2, recordSyncResult: recordSyncResult2, markSetupCopyRecovered: markSetupCopyRecovered2 } = (init_sync_state(), __toCommonJS(sync_state_exports));
    var FALLBACK_CHUNK_SIZE = 4 * 1024 * 1024;
    var syncBase = (plugin) => plugin.syncBaseUrl ? plugin.syncBaseUrl() : plugin.settings.syncApiBaseUrl;
    var deviceCredential = (plugin) => plugin.getDeviceCredential ? plugin.getDeviceCredential() : plugin.getSyncToken();
    var stateScope = (plugin) => plugin.syncStateScope ? plugin.syncStateScope() : void 0;
    async function sha256(buffer) {
      const digest = await crypto.subtle.digest("SHA-256", buffer);
      return Array.from(new Uint8Array(digest)).map((value) => value.toString(16).padStart(2, "0")).join("");
    }
    async function localManifest(plugin) {
      const entries = [];
      for (const file of plugin.app.vault.getFiles()) {
        if (classifyVaultPath2(file.path).scope !== "shared") continue;
        const bytes = await plugin.app.vault.adapter.readBinary(file.path);
        entries.push({ path: file.path, sha256: await sha256(bytes), size: bytes.byteLength, modifiedAt: new Date(file.stat.mtime).toISOString() });
      }
      return entries.sort((left, right) => left.path.localeCompare(right.path));
    }
    async function ensureParentDirectory(plugin, path) {
      const adapter = plugin.app.vault.adapter;
      const parts = path.split("/").slice(0, -1);
      let current = "";
      for (const part of parts) {
        current = current ? `${current}/${part}` : part;
        if (!await adapter.exists(current)) await adapter.mkdir(current);
      }
    }
    async function download(plugin, entry) {
      const condition = { "If-Match": `"${entry.sha256}"` };
      await ensureParentDirectory(plugin, entry.path);
      if (entry.size === 0) {
        const response = await syncRequest2(requestUrl, syncBase(plugin), deviceCredential(plugin), pathUrl2(entry.path), "GET", void 0, condition);
        await plugin.app.vault.adapter.writeBinary(entry.path, response.arrayBuffer);
        return;
      }
      const target = new Uint8Array(entry.size);
      for (let offset = 0; offset < entry.size; offset += FALLBACK_CHUNK_SIZE) {
        const end = Math.min(entry.size, offset + FALLBACK_CHUNK_SIZE) - 1;
        const response = await syncRequest2(requestUrl, syncBase(plugin), deviceCredential(plugin), pathUrl2(entry.path), "GET", void 0, { ...condition, Range: `bytes=${offset}-${end}` });
        const chunk = new Uint8Array(response.arrayBuffer);
        if (chunk.byteLength !== end - offset + 1) throw new Error("Vault sync download was truncated; refresh before retrying.");
        target.set(chunk, offset);
      }
      if (await sha256(target.buffer) !== entry.sha256) throw new Error("Vault sync download did not match the server digest.");
      await plugin.app.vault.adapter.writeBinary(entry.path, target.buffer);
    }
    async function preserveLocalConflict(plugin, path) {
      const adapter = plugin.app.vault.adapter;
      if (!await adapter.exists(path)) return void 0;
      const conflict = conflictPath2(path, plugin.settings.syncDeviceName || "device", (/* @__PURE__ */ new Date()).toISOString());
      await ensureParentDirectory(plugin, conflict);
      await adapter.writeBinary(conflict, await adapter.readBinary(path));
      return conflict;
    }
    function sameUpload(pending, local, remote) {
      return pending && pending.sha256 === local.sha256 && pending.size === local.size && pending.ifMatch === remote?.sha256 && pending.ifRevision === remote?.revision && Boolean(pending.ifNoneMatch) === !remote;
    }
    async function resumableUpload(plugin, local, remote) {
      const adapter = plugin.app.vault.adapter;
      const bytes = await adapter.readBinary(local.path);
      if (bytes.byteLength !== local.size || await sha256(bytes) !== local.sha256) throw new Error("The local file changed during synchronization; refresh before retrying.");
      const base = syncBase(plugin), token = deviceCredential(plugin);
      let pending = loadPendingUpload2(local.path, stateScope(plugin)), session;
      if (sameUpload(pending, local, remote)) {
        try {
          session = await uploadStatus2(requestUrl, base, token, pending.uploadId);
        } catch (_error) {
          pending = void 0;
        }
      }
      if (!session) {
        const start = { path: local.path, size: local.size, sha256: local.sha256, ...remote ? { ifMatch: remote.sha256, ...remote.revision ? { ifRevision: remote.revision } : {} } : { ifNoneMatch: true } };
        session = await startUpload2(requestUrl, base, token, start);
        pending = { uploadId: session.uploadId, path: local.path, sha256: local.sha256, size: local.size, ...remote ? { ifMatch: remote.sha256, ...remote.revision ? { ifRevision: remote.revision } : {} } : { ifNoneMatch: true } };
        savePendingUpload2(pending, stateScope(plugin));
      }
      if (session.size !== local.size || session.offset > local.size) throw new Error("The resumable upload state is incompatible; refresh before retrying.");
      while (session.offset < local.size) {
        const offset = session.offset, size = Math.min(session.chunkSize || FALLBACK_CHUNK_SIZE, local.size - offset);
        try {
          session = await uploadChunk2(requestUrl, base, token, session.uploadId, offset, bytes.slice(offset, offset + size));
        } catch (_error) {
          session = await uploadStatus2(requestUrl, base, token, session.uploadId);
        }
        if (session.offset <= offset || session.offset > local.size) throw new Error("The resumable upload did not advance; refresh before retrying.");
        savePendingUpload2(pending, stateScope(plugin));
      }
      await commitUpload2(requestUrl, base, token, session.uploadId);
      clearPendingUpload2(local.path, stateScope(plugin));
    }
    async function initialServerSync(plugin) {
      const remote = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      const adapter = plugin.app.vault.adapter;
      const result = { downloaded: 0, uploaded: 0, deleted: 0, conflicts: 0, skipped: 0 }, conflictPaths = [], conflictDetails = [];
      const remotePaths = new Set(remote.entries.map((entry) => entry.path));
      for (const entry of remote.entries) {
        if (classifyVaultPath2(entry.path).scope !== "shared") {
          result.skipped++;
          continue;
        }
        if (await adapter.exists(entry.path) && await sha256(await adapter.readBinary(entry.path)) !== entry.sha256) {
          const conflict = await preserveLocalConflict(plugin, entry.path);
          if (conflict) conflictPaths.push(conflict);
          result.conflicts++;
        }
        await download(plugin, entry);
        result.downloaded++;
      }
      for (const entry of await localManifest(plugin)) {
        if (remotePaths.has(entry.path)) continue;
        const conflict = await preserveLocalConflict(plugin, entry.path);
        if (conflict) conflictPaths.push(conflict);
        await adapter.remove(entry.path);
        result.conflicts++;
      }
      saveSyncState2(remote.entries, remote.revision, stateScope(plugin));
      if (typeof recordSyncResult2 === "function") recordSyncResult2({ ...result, conflictPaths }, stateScope(plugin));
      return result;
    }
    async function initialLocalImport(plugin) {
      const remote = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      const remoteByPath = new Map(remote.entries.map((entry) => [entry.path, entry]));
      const result = { downloaded: 0, uploaded: 0, deleted: 0, conflicts: 0, skipped: 0 }, conflictPaths = [];
      for (const entry of await localManifest(plugin)) {
        if (classifyVaultPath2(entry.path).scope !== "shared") {
          result.skipped++;
          continue;
        }
        const server = remoteByPath.get(entry.path);
        if (!server) {
          await resumableUpload(plugin, entry, void 0);
          result.uploaded++;
          continue;
        }
        if (server.sha256 === entry.sha256) continue;
        const conflict = await preserveLocalConflict(plugin, entry.path);
        if (conflict) conflictPaths.push(conflict);
        await download(plugin, server);
        result.downloaded++;
        result.conflicts++;
      }
      const completed = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      saveSyncState2(completed.entries, completed.revision, stateScope(plugin));
      if (typeof recordSyncResult2 === "function") recordSyncResult2({ ...result, conflictPaths }, stateScope(plugin));
      return result;
    }
    async function recoverableSetupCopies(plugin) {
      const remote = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      const remotePaths = new Set(remote.entries.map((entry) => entry.path));
      const adapter = plugin.app.vault.adapter;
      const copies = [];
      for (const file of plugin.app.vault.getFiles()) {
        const originalPath = sourcePathForConflictCopy2(file.path);
        if (!originalPath || classifyVaultPath2(originalPath).scope !== "shared") continue;
        if (await adapter.exists(originalPath) || remotePaths.has(originalPath)) continue;
        copies.push({ conflictPath: file.path, originalPath });
      }
      return copies.sort((left, right) => left.originalPath.localeCompare(right.originalPath));
    }
    async function recoverSetupCopies(plugin, requestedCopies) {
      const candidates = await recoverableSetupCopies(plugin);
      const requested = new Set((requestedCopies || []).map((copy) => typeof copy === "string" ? copy : copy?.conflictPath));
      const copies = requested.size ? candidates.filter((copy) => requested.has(copy.conflictPath)) : candidates;
      const adapter = plugin.app.vault.adapter;
      const result = { restored: 0, uploaded: 0, skipped: candidates.length - copies.length };
      for (const copy of copies) {
        if (!await adapter.exists(copy.conflictPath) || await adapter.exists(copy.originalPath)) {
          result.skipped++;
          continue;
        }
        const bytes = await adapter.readBinary(copy.conflictPath);
        await ensureParentDirectory(plugin, copy.originalPath);
        await adapter.writeBinary(copy.originalPath, bytes);
        const local = { path: copy.originalPath, sha256: await sha256(bytes), size: bytes.byteLength, modifiedAt: (/* @__PURE__ */ new Date()).toISOString() };
        await resumableUpload(plugin, local, void 0);
        result.restored++;
        result.uploaded++;
        if (typeof markSetupCopyRecovered2 === "function") markSetupCopyRecovered2(copy.conflictPath, stateScope(plugin));
      }
      const completed = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      saveSyncState2(completed.entries, completed.revision, stateScope(plugin));
      return result;
    }
    async function syncNow(plugin) {
      const state = loadSyncState2(stateScope(plugin));
      if (!state) throw new Error("Run Initial server-authoritative vault sync before ordinary synchronization.");
      const remote = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      const local = await localManifest(plugin);
      const result = { downloaded: 0, uploaded: 0, deleted: 0, conflicts: 0, skipped: 0 }, conflictPaths = [], conflictDetails = [];
      for (const action of reconcile2(state.entries, local, remote.entries)) {
        if (action.kind === "none") continue;
        if (classifyVaultPath2(action.path).scope !== "shared") {
          result.skipped++;
          continue;
        }
        if (action.kind === "download") {
          await download(plugin, action.remote);
          result.downloaded++;
          continue;
        }
        if (action.kind === "delete-local") {
          await plugin.app.vault.adapter.remove(action.path);
          result.deleted++;
          continue;
        }
        if (action.kind === "upload") {
          await resumableUpload(plugin, action.local, action.remote);
          result.uploaded++;
          continue;
        }
        if (action.kind === "delete-remote") {
          await syncRequest2(requestUrl, syncBase(plugin), deviceCredential(plugin), pathUrl2(action.path), "DELETE", void 0, { "If-Match": `"${action.remote.sha256}"`, ...action.remote.revision ? { "X-NAS-Revision": action.remote.revision } : {} });
          result.deleted++;
          continue;
        }
        const conflict = await preserveLocalConflict(plugin, action.path);
        if (conflict) conflictPaths.push(conflict);
        conflictDetails.push({ path: action.path, conflictPath: conflict, base: action.base, local: action.local, remote: action.remote });
        result.conflicts++;
        if (action.remote) {
          await download(plugin, action.remote);
          result.downloaded++;
        } else await plugin.app.vault.adapter.remove(action.path);
      }
      const completed = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      saveSyncState2(completed.entries, completed.revision, stateScope(plugin));
      if (typeof recordSyncResult2 === "function") recordSyncResult2({ ...result, conflictPaths, conflictDetails }, stateScope(plugin));
      return result;
    }
    async function renameNow(plugin, oldPath, newPath) {
      const state = loadSyncState2(stateScope(plugin));
      if (!state) return false;
      const base = state.entries.find((entry) => entry.path === oldPath);
      if (!base || !await plugin.app.vault.adapter.exists(newPath)) return false;
      const remote = (await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin))).entries.find((entry) => entry.path === oldPath);
      if (!remote || remote.sha256 !== base.sha256) return false;
      await renameRemote2(requestUrl, syncBase(plugin), deviceCredential(plugin), oldPath, newPath, remote.sha256, remote.revision);
      const completed = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      saveSyncState2(completed.entries, completed.revision, stateScope(plugin));
      return true;
    }
    async function resolveConflict(plugin, issue, choice) {
      const remote = issue?.remote;
      if (!remote || !issue.path) throw new Error("This conflict no longer has a usable server revision.");
      if (choice === "server" || choice === "both") await download(plugin, remote);
      if (choice === "local") {
        const bytes = await plugin.app.vault.adapter.readBinary(issue.path);
        const local = { path: issue.path, sha256: await sha256(bytes), size: bytes.byteLength, modifiedAt: (/* @__PURE__ */ new Date()).toISOString() };
        await resumableUpload(plugin, local, remote);
      }
      const completed = await manifest2(requestUrl, syncBase(plugin), deviceCredential(plugin));
      saveSyncState2(completed.entries, completed.revision, stateScope(plugin));
      return completed;
    }
    module2.exports = { initialServerSync, initialLocalImport, recoverableSetupCopies, recoverSetupCopies, syncNow, localManifest, renameNow, resolveConflict };
  }
});

// src/overview.js
var require_overview = __commonJS({
  "src/overview.js"(exports2, module2) {
    var { ItemView, Modal, Notice, Setting } = require("obsidian");
    var { loadSyncState: loadSyncState2, loadSyncIssues: loadSyncIssues2, markIssueReviewed: markIssueReviewed2 } = (init_sync_state(), __toCommonJS(sync_state_exports));
    var { recoverableSetupCopies } = require_sync_engine();
    var CONTROL_CENTER_VIEW_TYPE = "nas-vault-control-center";
    function statusFor(plugin, connection) {
      if (!plugin.getDeviceCredential()) return { tone: "grey", label: "No account connected", detail: "Connect this device to an existing account or register a new one." };
      if (!connection?.calendar || !connection?.sync || !connection?.device) return { tone: "red", label: "NAS unavailable", detail: "This device is signed in, but the NAS cannot be reached or no longer accepts its access." };
      if (plugin.vaultSyncRunning) return { tone: "blue", label: "Syncing", detail: "Reconciling this device with your private server vault." };
      if (!plugin.settings.initialSyncCompleted || !loadSyncState2(plugin.syncStateScope())) return { tone: "yellow", label: "Initial sync needed", detail: "The account is connected; choose whether this device imports its vault or begins from the server vault." };
      return { tone: "green", label: "Synced and healthy", detail: "NAS services are reachable and the latest local sync state is ready." };
    }
    var NasControlCenterView = class extends ItemView {
      constructor(leaf, plugin) {
        super(leaf);
        this.plugin = plugin;
      }
      getViewType() {
        return CONTROL_CENTER_VIEW_TYPE;
      }
      getDisplayText() {
        return "NAS Vault";
      }
      getIcon() {
        return "server";
      }
      async onOpen() {
        await this.render();
      }
      async onClose() {
        this.contentEl.empty();
      }
      async render() {
        const el = this.contentEl;
        el.empty();
        el.addClass("nas-vault-control-center");
        el.createEl("h1", { text: "NAS Vault" });
        const data = await this.loadProfile(), status = statusFor(this.plugin, data.connection);
        const header = el.createDiv({ cls: `nas-vault-status nas-vault-status--${status.tone}` });
        header.createSpan({ cls: "nas-vault-status__dot" });
        const copy = header.createDiv();
        copy.createEl("strong", { text: data.profile?.username || "No account connected" });
        copy.createEl("span", { text: status.label });
        el.createEl("p", { text: status.detail, cls: "nas-vault-status__detail" });
        const actions = el.createDiv({ cls: "nas-vault-actions" });
        const action = (label, callback, primary = false) => {
          const button = actions.createEl("button", { text: label, cls: primary ? "mod-cta" : "" });
          button.onclick = () => void callback();
        };
        if (!this.plugin.getDeviceCredential()) action("Connect this device", () => this.plugin.connectViaMultiUserEnrollment(), true);
        else if (!this.plugin.settings.initialSyncCompleted || !loadSyncState2(this.plugin.syncStateScope())) {
          action("Set up vault sync", async () => {
            await this.plugin.chooseInitialSync();
            await this.render();
          }, true);
          action("Open calendar", () => this.plugin.openCalendar());
          action("Refresh status", () => this.render());
        } else {
          action("Sync now", async () => {
            await this.plugin.syncVaultNow();
            await this.render();
          }, true);
          action("Open calendar", () => this.plugin.openCalendar());
          action("Refresh status", () => this.render());
        }
        if (data.profile) this.renderAccount(el, data.profile);
        await this.renderIssues(el, status);
      }
      async loadProfile() {
        if (!this.plugin.getDeviceCredential()) return { profile: null, connection: null };
        const [account, connection] = await Promise.allSettled([this.plugin.accountSummary(), this.plugin.checkNasConnection({ silent: true })]);
        return { profile: account.status === "fulfilled" ? account.value : null, connection: connection.status === "fulfilled" ? connection.value : null };
      }
      renderAccount(el, profile) {
        const current = profile.currentDevice || {};
        el.createEl("h2", { text: "This device" });
        new Setting(el).setName(current.name || "Connected device").setDesc(`Account: ${profile.username}`).addButton((b) => b.setButtonText("Rename").onClick(async () => {
          const name = window.prompt("New device name", current.name || "");
          if (!name) return;
          try {
            await this.plugin.renameThisDevice(name);
            await this.render();
          } catch (error) {
            new Notice(error.message || String(error));
          }
        }));
        el.createEl("h2", { text: `Devices (${(profile.devices || []).length})` });
        for (const item of profile.devices || []) new Setting(el).setName(item.name).setDesc(item.id === current.id ? "This device" : "Active device").addButton((b) => b.setButtonText("Revoke").setWarning().setDisabled(item.id === current.id).onClick(async () => {
          if (!window.confirm(`Revoke ${item.name}?`)) return;
          try {
            await this.plugin.revokeActiveDevice(item.name);
            await this.render();
          } catch (error) {
            new Notice(error.message || String(error));
          }
        }));
        new Setting(el).setName("Account").setDesc("Logging out removes this device\u2019s local login only. Server content remains.").addButton((b) => b.setButtonText("Log out").setWarning().onClick(async () => {
          if (!window.confirm("Log out from this device?")) return;
          await this.plugin.disconnectThisDevice();
          await this.render();
        }));
        new Setting(el).setName("Account data").setDesc("Export includes current files, immutable revisions, and quarantined deletions. Imports never overwrite existing files.").addButton((b) => b.setButtonText("Export account").onClick(async () => {
          try {
            await this.plugin.exportAccountArchive();
          } catch (error) {
            new Notice(error.message || String(error));
          }
        })).addButton((b) => b.setButtonText("Import account").onClick(() => {
          const input = document.createElement("input");
          input.type = "file";
          input.accept = ".zip,application/zip";
          input.onchange = async () => {
            const file = input.files?.[0];
            if (!file) return;
            try {
              const preview = await this.plugin.importAccountArchive(file, true);
              if (!window.confirm(`Import ${preview.wouldCreate?.length || 0} new files? Existing files will be skipped.`)) return;
              const result = await this.plugin.importAccountArchive(file, false);
              new Notice(`Imported ${result.created?.length || 0} files; skipped ${result.skipped?.length || 0}.`);
              await this.render();
            } catch (error) {
              new Notice(error.message || String(error));
            }
          };
          input.click();
        })).addButton((b) => b.setButtonText("Revision history").onClick(() => new HistoryModal(this.app, this.plugin).open()));
      }
      async renderIssues(el, status) {
        let protectedCopies = [];
        try {
          protectedCopies = await recoverableSetupCopies(this.plugin);
        } catch (_error) {
        }
        const protectedPaths = new Set(protectedCopies.map((copy) => copy.conflictPath));
        const issues = loadSyncIssues2(this.plugin.syncStateScope()).filter((item) => !item.reviewed && !protectedPaths.has(item.path) && !protectedPaths.has(item.conflictPath));
        if (protectedCopies.length) {
          el.createEl("h2", { text: "Protected setup copies" });
          el.createEl("p", { text: "These copies were protected while this new account had no matching server files. Restoring sends a new original copy to this account and keeps the protected copy for verification.", cls: "nas-vault-issues" });
          new Setting(el).setName(`${protectedCopies.length} recoverable ${protectedCopies.length === 1 ? "file" : "files"}`).setDesc("Each original path is absent both locally and on the NAS. Existing files are never overwritten.").addButton((b) => b.setButtonText("Restore all to account").setCta().onClick(async () => {
            if (!window.confirm(`Restore ${protectedCopies.length} protected setup ${protectedCopies.length === 1 ? "copy" : "copies"} to this account? Each protected copy will be kept.`)) return;
            await this.plugin.recoverSetupCopies(protectedCopies);
            await this.render();
          }));
          for (const copy of protectedCopies) new Setting(el).setName(copy.originalPath).setDesc(`Protected file: ${copy.conflictPath}`).addButton((b) => b.setButtonText("Restore to account").onClick(async () => {
            if (!window.confirm(`Restore ${copy.originalPath} to this account? The protected copy will be kept.`)) return;
            await this.plugin.recoverSetupCopies([copy]);
            await this.render();
          }));
        }
        el.createEl("h2", { text: "Needs attention" });
        if (!issues.length) {
          el.createEl("p", { text: protectedCopies.length ? "No active sync conflicts." : status.tone === "green" ? "No action needed." : status.detail, cls: "nas-vault-issues" });
          return;
        }
        for (const issue of issues) {
          const row = new Setting(el).setName(issue.kind === "conflict" ? `Conflict: ${issue.path || "file"}` : "Sync failed").setDesc(issue.detail);
          if (issue.kind === "conflict" && issue.remote?.revision) row.addButton((b) => b.setButtonText("Compare / resolve").setCta().onClick(() => new ConflictModal(this.app, this.plugin, issue, () => this.render()).open()));
          row.addButton((b) => b.setButtonText("Mark reviewed").onClick(async () => {
            markIssueReviewed2(issue.id, this.plugin.syncStateScope());
            await this.render();
          }));
        }
        try {
          const deleted = await this.plugin.accountTrash();
          if (deleted.length) {
            el.createEl("h2", { text: "Deleted files (30-day restore)" });
            for (const item of deleted) new Setting(el).setName(item.path).setDesc(`Deleted ${new Date(item.acceptedAt).toLocaleString()} \xB7 expires ${new Date(item.purgeAt).toLocaleString()}`).addButton((b) => b.setButtonText("Restore").onClick(async () => {
              try {
                await this.plugin.restoreDeletedRevision(item.revision);
                new Notice(`Restored ${item.path}`);
                await this.render();
              } catch (error) {
                new Notice(error.message || String(error));
              }
            }));
          }
        } catch (_error) {
        }
      }
    };
    var ConflictModal = class extends Modal {
      constructor(app, plugin, issue, onDone) {
        super(app);
        this.plugin = plugin;
        this.issue = issue;
        this.onDone = onDone;
      }
      async onOpen() {
        const el = this.contentEl;
        el.empty();
        el.createEl("h2", { text: `Resolve conflict: ${this.issue.path}` });
        const status = el.createEl("p", { text: "Loading server revision\u2026" });
        let remoteText = "(binary or unavailable)";
        try {
          const bytes = await this.plugin.revisionBytes(this.issue.remote.revision);
          const decoded = new TextDecoder().decode(bytes);
          if (!decoded.includes("\0")) remoteText = decoded;
        } catch (_error) {
          status.setText("The server revision is no longer available.");
        }
        status.setText("Local copy is preserved separately. Review both versions, then choose a resolution.");
        const grid = el.createDiv({ cls: "nas-vault-conflict-compare" });
        let localText = `(local copy unavailable)
${this.issue.local?.sha256 || "unknown digest"}`;
        try {
          const bytes = await this.plugin.app.vault.adapter.readBinary(this.issue.path);
          const decoded = new TextDecoder().decode(bytes);
          if (!decoded.includes("\0")) localText = decoded;
        } catch (_error) {
        }
        grid.createEl("pre", { text: `LOCAL
${this.issue.path}

${localText.slice(0, 12e3)}` });
        grid.createEl("pre", { text: `SERVER REVISION
${this.issue.remote.revision}

${remoteText.slice(0, 12e3)}` });
        const merged = el.createEl("textarea", { cls: "nas-vault-conflict-merge" });
        merged.value = remoteText;
        const actions = el.createDiv({ cls: "nas-vault-actions" });
        const finish = async (choice) => {
          try {
            if (choice === "merge") {
              await this.plugin.app.vault.adapter.write(this.issue.path, merged.value);
              choice = "local";
            }
            await this.plugin.resolveConflict(this.issue, choice);
            new Notice("Conflict resolved and revision recorded.");
            this.close();
            this.onDone();
          } catch (error) {
            new Notice(error.message || String(error));
          }
        };
        for (const [label, choice] of [["Keep local", "local"], ["Keep server", "server"], ["Keep both", "both"], ["Save merged text", "merge"]]) {
          const b = actions.createEl("button", { text: label });
          b.onclick = () => void finish(choice);
        }
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    var HistoryModal = class extends Modal {
      constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
      }
      async onOpen() {
        const el = this.contentEl;
        el.empty();
        el.createEl("h2", { text: "Immutable revision history" });
        const status = el.createEl("p", { text: "Loading\u2026" });
        try {
          const entries = await this.plugin.accountHistory();
          status.setText(entries.length ? "Every accepted server revision is retained here." : "No revisions yet.");
          for (const item of entries.slice(0, 100)) new Setting(el).setName(item.path).setDesc(`${item.kind || "update"} \xB7 ${item.revision} \xB7 ${new Date(item.acceptedAt).toLocaleString()}`).addButton((b) => b.setButtonText("Download").onClick(async () => {
            try {
              const bytes = await this.plugin.revisionBytes(item.revision);
              const safe = item.path.replace(/[^A-Za-z0-9_.-]+/g, "_");
              const path = `.nas-vault-sync/revision-${item.revision}-${safe}`;
              await this.plugin.app.vault.adapter.mkdir(".nas-vault-sync").catch(() => void 0);
              await this.plugin.app.vault.adapter.writeBinary(path, bytes);
              new Notice(`Revision saved to ${path}`);
            } catch (error) {
              new Notice(error.message || String(error));
            }
          }));
        } catch (error) {
          status.setText(error.message || "History unavailable while offline.");
        }
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    module2.exports = { NasControlCenterView, CONTROL_CENTER_VIEW_TYPE, statusFor };
  }
});

// src/service-url.ts
var service_url_exports = {};
__export(service_url_exports, {
  SERVICE_PATHS: () => SERVICE_PATHS,
  inferNasBaseUrl: () => inferNasBaseUrl,
  migrateNasBaseUrl: () => migrateNasBaseUrl,
  normalizeNasBaseUrl: () => normalizeNasBaseUrl,
  serviceBaseUrl: () => serviceBaseUrl
});
function parsePrivateBaseUrl(value) {
  const trimmed = value.trim();
  let parsed;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw new Error("Configure a valid private NAS base URL.");
  }
  if (!trimmed || !["http:", "https:"].includes(parsed.protocol) || parsed.username || parsed.password || parsed.search || parsed.hash) {
    throw new Error("Use an HTTP or HTTPS NAS base URL without credentials, query, or fragment.");
  }
  return parsed;
}
function formatBaseUrl(parsed) {
  const path = parsed.pathname.replace(/\/+$/, "");
  return `${parsed.origin}${path === "/" ? "" : path}`;
}
function normalizeNasBaseUrl(value) {
  return formatBaseUrl(parsePrivateBaseUrl(value));
}
function serviceBaseUrl(base, service) {
  const path = SERVICE_PATHS[service];
  if (!path) throw new Error("Unknown NAS service.");
  return normalizeNasBaseUrl(base) + path;
}
function inferNasBaseUrl(value) {
  const parsed = parsePrivateBaseUrl(value);
  let path = parsed.pathname.replace(/\/+$/, "");
  for (const suffix of LEGACY_SERVICE_SUFFIXES) {
    if (path === suffix) {
      path = "";
      break;
    }
    if (path.endsWith(suffix)) {
      path = path.slice(0, -suffix.length);
      break;
    }
  }
  parsed.pathname = path || "/";
  return formatBaseUrl(parsed);
}
function migrateNasBaseUrl(current, legacy = {}) {
  const candidate = typeof current === "string" && current.trim() ? current : [legacy.apiBaseUrl, legacy.syncApiBaseUrl, legacy.enrollmentPortalUrl].find((value) => typeof value === "string" && Boolean(value.trim())) || "";
  if (!candidate) return "";
  try {
    return inferNasBaseUrl(candidate);
  } catch {
    return candidate.trim();
  }
}
var SERVICE_PATHS, LEGACY_SERVICE_SUFFIXES;
var init_service_url = __esm({
  "src/service-url.ts"() {
    SERVICE_PATHS = {
      calendar: "/calendar-api",
      sync: "/vault-sync",
      enrollment: "/vault-enroll"
    };
    LEGACY_SERVICE_SUFFIXES = [
      "/calendar-api",
      "/vault-sync",
      "/vault-sync-pilot",
      "/vault-enroll",
      "/vault-enroll-pilot",
      "/enrollment"
    ];
  }
});

// src/calendar.js
var require_calendar = __commonJS({
  "src/calendar.js"(exports2, module2) {
    "use strict";
    var {
      ItemView,
      Modal,
      Notice,
      Plugin,
      PluginSettingTab,
      Setting,
      requestUrl,
      normalizePath
    } = require("obsidian");
    var { requestApi: requestApi2 } = (init_api(), __toCommonJS(api_exports));
    var { syncRequest: syncRequest2, exportAccount: exportAccount2, importAccount: importAccount2, history: history2, trash: trash2, revisionContent: revisionContent2, restoreRevision: restoreRevision2 } = (init_sync_api(), __toCommonJS(sync_api_exports));
    var { initialServerSync, initialLocalImport, recoverSetupCopies, renameNow, resolveConflict } = require_sync_engine();
    var { syncNow } = require_sync_engine();
    var { loadSyncState: loadSyncState2 } = (init_sync_state(), __toCommonJS(sync_state_exports));
    var { NasControlCenterView, CONTROL_CENTER_VIEW_TYPE } = require_overview();
    var { migrateNasBaseUrl: migrateNasBaseUrl2, serviceBaseUrl: serviceBaseUrl2 } = (init_service_url(), __toCommonJS(service_url_exports));
    var VIEW_TYPE = "nas-calendar-bridge-view";
    var LEGACY_PLUGIN_ID = "nas-calendar-bridge";
    var DEVICE_CREDENTIAL_KEY = "mynasbridge.device-credential.v2";
    var API_VERSION = 1;
    var DEFAULT_SETTINGS = {
      nasBaseUrl: "",
      diaryRoot: "Mateos Vault/03_Diary",
      weekStartsMonday: true,
      syncDeviceName: "",
      autoInitialSyncAfterPairing: true,
      initialSyncCompleted: false,
      automaticVaultSync: false,
      automaticVaultSyncIntervalSeconds: 30
    };
    var CalendarApiError = class extends Error {
      constructor(message, status) {
        super(message);
        this.name = "CalendarApiError";
        this.status = status;
      }
    };
    var NasCalendarBridge = class extends Plugin {
      async onload() {
        const currentData = await this.loadData();
        const legacyData = currentData ? void 0 : await loadLegacySettings(this.app);
        const sourceData = currentData || legacyData || {};
        this.settings = migrateSettings(sourceData);
        this.localScope = localVaultScope(this.app);
        const hasLegacyUrl = ["apiBaseUrl", "syncApiBaseUrl", "enrollmentPortalUrl"].some((key) => Object.prototype.hasOwnProperty.call(sourceData, key));
        if (!currentData || hasLegacyUrl || this.settings.nasBaseUrl !== sourceData.nasBaseUrl) await this.saveData(this.settings);
        this.registerView(VIEW_TYPE, (leaf) => new CalendarView(leaf, this));
        this.registerView(CONTROL_CENTER_VIEW_TYPE, (leaf) => new NasControlCenterView(leaf, this));
        this.addRibbonIcon("server", "Open NAS Vault", () => this.openNasControlCenter());
        this.addCommand({ id: "open-nas-overview", name: "Open NAS Vault", callback: () => this.openNasControlCenter() });
        this.addCommand({
          id: "open-calendar",
          name: "Open calendar",
          callback: () => this.openCalendar()
        });
        this.addCommand({ id: "initial-server-vault-sync", name: "Initial server-authoritative vault sync", callback: () => this.initialServerSync() });
        this.addCommand({ id: "initial-local-vault-import", name: "Initial local vault import", callback: () => this.initialLocalImport() });
        this.addCommand({ id: "sync-vault-now", name: "Sync vault now", callback: () => this.syncVaultNow() });
        this.addCommand({ id: "test-vault-sync-connection", name: "Test vault-sync connection", callback: () => this.testSyncConnection() });
        this.addCommand({
          id: "refresh-calendar",
          name: "Refresh NAS calendar",
          callback: () => this.refreshViews()
        });
        this.addCommand({
          id: "create-calendar-event",
          name: "Create calendar event",
          callback: () => new EventModal(this.app, this, null, localDateKey(/* @__PURE__ */ new Date())).open()
        });
        this.addCommand({
          id: "open-todays-daily-note",
          name: "Open today's daily note (server-routed)",
          callback: () => this.openDailyNote(localDateKey(/* @__PURE__ */ new Date()))
        });
        this.addSettingTab(new CalendarBridgeSettingsTab(this.app, this));
        this.registerEvent(this.app.workspace.on("file-open", () => this.refreshViews()));
        this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
          void (async () => {
            const handled = await renameNow(this, oldPath, file.path).catch(() => false);
            if (!handled) this.scheduleVaultSync();
          })();
        }));
        for (const event of ["modify", "create", "delete"]) this.registerEvent(this.app.vault.on(event, () => this.scheduleVaultSync()));
        if (typeof window !== "undefined" && typeof this.registerDomEvent === "function") {
          this.registerDomEvent(window, "focus", () => void this.syncOnResume());
          this.registerDomEvent(document, "visibilitychange", () => {
            if (!document.hidden) void this.syncOnResume();
          });
          window.setTimeout(() => void this.syncOnResume(), 1200);
        }
        this.startVaultSyncPolling();
      }
      onunload() {
        this.stopVaultSyncPolling();
        if (this.vaultSyncTimer) window.clearTimeout(this.vaultSyncTimer);
        this.app.workspace.detachLeavesOfType(VIEW_TYPE);
        this.app.workspace.detachLeavesOfType(CONTROL_CENTER_VIEW_TYPE);
      }
      async saveSettings() {
        await this.saveData(this.settings);
        await this.refreshViews();
      }
      credentialStorageKey() {
        return `${DEVICE_CREDENTIAL_KEY}.${this.localScope}`;
      }
      syncStateScope() {
        const credential = this.getDeviceCredential();
        return credential ? `${this.localScope}.${localStateHash(credential)}` : this.localScope;
      }
      syncBaseUrl() {
        return serviceBaseUrl2(this.settings.nasBaseUrl, "sync");
      }
      getDeviceCredential() {
        try {
          return window.localStorage.getItem(this.credentialStorageKey()) || "";
        } catch (_error) {
          return "";
        }
      }
      setDeviceCredential(token) {
        try {
          if (token) window.localStorage.setItem(this.credentialStorageKey(), token);
          else window.localStorage.removeItem(this.credentialStorageKey());
        } catch (_error) {
          new Notice("Could not access this device's local credential storage.");
        }
      }
      // Compatibility aliases for the existing modules while all new flows use one grant.
      getToken() {
        return this.getDeviceCredential();
      }
      getSyncToken() {
        return this.getDeviceCredential();
      }
      setToken(token) {
        this.setDeviceCredential(token);
      }
      setSyncToken(token) {
        this.setDeviceCredential(token);
      }
      async apiRequest(path, method = "GET", body = void 0) {
        return requestApi2(requestUrl, serviceBaseUrl2(this.settings.nasBaseUrl, "calendar"), this.getToken(), path, method, body);
      }
      async getEvents(start, end) {
        const query = new URLSearchParams({ apiVersion: String(API_VERSION), start, end });
        const data = await this.apiRequest(`/v1/events?${query.toString()}`);
        if (!data || data.apiVersion !== API_VERSION || !Array.isArray(data.events)) {
          throw new CalendarApiError("Calendar API returned an unsupported response.");
        }
        return data.events;
      }
      async health() {
        return this.apiRequest(`/v1/health?apiVersion=${API_VERSION}`);
      }
      async syncHealth() {
        const response = await syncRequest2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential(), "/sync/v1/health");
        try {
          return JSON.parse(response.text);
        } catch (_error) {
          throw new Error("Vault sync health returned an invalid response.");
        }
      }
      async checkNasConnection(options = {}) {
        const [calendar, sync, heartbeat] = await Promise.allSettled([this.health(), this.syncHealth(), this.touchDevice()]);
        const result = {
          calendar: calendar.status === "fulfilled" && calendar.value?.status === "ok",
          sync: sync.status === "fulfilled" && sync.value?.status === "ok",
          device: heartbeat.status === "fulfilled" && heartbeat.value?.status === "ok"
        };
        if (!options.silent) new Notice(`NAS connection: calendar ${result.calendar ? "connected" : "unavailable"}; vault sync ${result.sync ? "connected" : "unavailable"}.`);
        return result;
      }
      async touchDevice() {
        return enrollmentRequest(serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment"), "/api/v2/device/heartbeat", "POST", {}, this.getDeviceCredential());
      }
      async activeDevices() {
        return enrollmentRequest(serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment"), "/api/v2/device/list-active", "POST", {}, this.getDeviceCredential());
      }
      async accountSummary() {
        return enrollmentRequest(serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment"), "/api/v2/account/me", "POST", {}, this.getDeviceCredential());
      }
      async renameThisDevice(name) {
        const result = await enrollmentRequest(serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment"), "/api/v2/device/rename-active", "POST", { deviceName: name }, this.getDeviceCredential());
        this.settings.syncDeviceName = result.deviceName;
        await this.saveSettings();
        return result;
      }
      async disconnectThisDevice() {
        this.setDeviceCredential("");
        this.settings.initialSyncCompleted = false;
        await this.saveSettings();
      }
      async openNasControlCenter() {
        let leaf = this.app.workspace.getLeavesOfType(CONTROL_CENTER_VIEW_TYPE)[0];
        if (!leaf) leaf = this.app.workspace.getLeaf("tab");
        await leaf.setViewState({ type: CONTROL_CENTER_VIEW_TYPE, active: true });
        this.app.workspace.revealLeaf(leaf);
      }
      async revokeActiveDevice(name) {
        return enrollmentRequest(serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment"), "/api/v2/device/revoke-active", "POST", { deviceName: name }, this.getDeviceCredential());
      }
      async testSyncConnection() {
        try {
          const health = await this.syncHealth();
          new Notice(`Vault sync healthy (contract v${health.apiVersion || "?"}).`);
          return health;
        } catch (error) {
          new Notice(error.message || String(error));
          throw error;
        }
      }
      async exportAccountArchive() {
        const bytes = await exportAccount2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential());
        const path = `.nas-vault-sync/account-export-${(/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-")}.zip`;
        await this.app.vault.adapter.mkdir(".nas-vault-sync").catch(() => void 0);
        await this.app.vault.adapter.writeBinary(path, bytes);
        new Notice(`Account export saved to ${path}. Keep it private.`);
        return path;
      }
      async importAccountArchive(file, dryRun = false) {
        const bytes = await file.arrayBuffer();
        const result = await importAccount2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential(), bytes, dryRun);
        return result;
      }
      async accountHistory(path) {
        return history2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential(), path);
      }
      async accountTrash() {
        return trash2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential());
      }
      async restoreDeletedRevision(revision) {
        return restoreRevision2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential(), revision);
      }
      async revisionBytes(revision) {
        return revisionContent2(requestUrl, this.syncBaseUrl(), this.getDeviceCredential(), revision);
      }
      async resolveConflict(issue, choice) {
        const result = await resolveConflict(this, issue, choice);
        const { loadSyncIssues: loadSyncIssues2, saveSyncIssues: saveSyncIssues2 } = (init_sync_state(), __toCommonJS(sync_state_exports));
        saveSyncIssues2(loadSyncIssues2(this.syncStateScope()).map((item) => item.id === issue.id ? { ...item, reviewed: true } : item), this.syncStateScope());
        return result;
      }
      async connectViaMultiUserEnrollment() {
        let portal;
        try {
          portal = serviceBaseUrl2(this.settings.nasBaseUrl, "enrollment");
        } catch (_error) {
          new Notice("Configure the private NAS base URL first.");
          return;
        }
        if (!this.settings.syncDeviceName.trim()) {
          new Notice("Choose this device's sync name first.");
          return;
        }
        try {
          const pairing = await enrollmentRequest(portal, "/api/v2/pairing/start", "POST", { deviceName: this.settings.syncDeviceName.trim() });
          if (pairing.apiVersion !== 2 || typeof pairing.pairingCode !== "string" || typeof pairing.pollToken !== "string") {
            throw new Error("Enrollment portal returned an incompatible response.");
          }
          new PortalEnrollmentModal(this.app, this, portal, pairing).open();
        } catch (error) {
          new Notice(error.message || String(error));
        }
      }
      async initialServerSync(options = {}) {
        if (this.vaultSyncRunning) return;
        if (options.confirm !== false && !window.confirm("Download the server vault now? Local files that differ will be preserved as conflict copies.")) return;
        this.vaultSyncRunning = true;
        try {
          const result = await initialServerSync(this);
          this.settings.initialSyncCompleted = true;
          await this.saveSettings();
          new Notice(`Vault sync complete: ${result.downloaded} downloaded, ${result.conflicts} conflicts preserved.`);
          return result;
        } catch (error) {
          new Notice(error.message || String(error));
        } finally {
          this.vaultSyncRunning = false;
        }
      }
      async initialLocalImport() {
        if (this.vaultSyncRunning) return;
        this.vaultSyncRunning = true;
        try {
          const result = await initialLocalImport(this);
          this.settings.initialSyncCompleted = true;
          await this.saveSettings();
          new Notice(`Local vault imported: ${result.uploaded} uploaded, ${result.conflicts} existing server files preserved.`);
          return result;
        } catch (error) {
          new Notice(error.message || String(error));
        } finally {
          this.vaultSyncRunning = false;
        }
      }
      async recoverSetupCopies(copies) {
        if (this.vaultSyncRunning) return;
        this.vaultSyncRunning = true;
        try {
          const result = await recoverSetupCopies(this, copies);
          this.settings.initialSyncCompleted = true;
          await this.saveSettings();
          new Notice(`Recovered ${result.restored} protected setup ${result.restored === 1 ? "copy" : "copies"} into this account. The protected copies remain for verification.`);
          return result;
        } catch (error) {
          new Notice(error.message || String(error));
        } finally {
          this.vaultSyncRunning = false;
        }
      }
      async chooseInitialSync() {
        const importLocal = window.confirm("This is the first sync for this device. Press OK to import this device's shared vault into the new server account. Press Cancel to start from the server vault instead.");
        return importLocal ? this.initialLocalImport() : this.initialServerSync({ confirm: false });
      }
      async syncVaultNow(options = {}) {
        if (this.vaultSyncRunning) return;
        this.vaultSyncRunning = true;
        try {
          const result = await syncNow(this);
          if (!options.silent) new Notice(`Vault sync: ${result.downloaded} downloaded, ${result.uploaded} uploaded, ${result.deleted} deleted, ${result.conflicts} conflicts.`);
          return result;
        } catch (error) {
          if (!options.silent) new Notice(error.message || String(error));
        } finally {
          this.vaultSyncRunning = false;
        }
      }
      async syncOnResume() {
        if (!this.settings.nasBaseUrl || !this.getDeviceCredential()) return;
        await this.checkNasConnection({ silent: true });
        if (this.settings.automaticVaultSync && loadSyncState2(this.syncStateScope())) await this.syncVaultNow({ silent: true });
      }
      scheduleVaultSync() {
        if (!this.settings.automaticVaultSync || this.vaultSyncRunning || !loadSyncState2(this.syncStateScope())) return;
        window.clearTimeout(this.vaultSyncTimer);
        this.vaultSyncTimer = window.setTimeout(() => this.syncVaultNow({ silent: true }), 3e3);
      }
      startVaultSyncPolling() {
        this.stopVaultSyncPolling();
        if (!this.settings.automaticVaultSync || typeof window === "undefined") return;
        const seconds = Math.max(10, Math.min(3600, Number(this.settings.automaticVaultSyncIntervalSeconds) || 30));
        this.vaultSyncPollTimer = window.setInterval(() => {
          if (loadSyncState2(this.syncStateScope())) void this.syncVaultNow({ silent: true });
        }, seconds * 1e3);
      }
      stopVaultSyncPolling() {
        if (this.vaultSyncPollTimer && typeof window !== "undefined") window.clearInterval(this.vaultSyncPollTimer);
        this.vaultSyncPollTimer = void 0;
      }
      async ensureDailyNote(date) {
        return this.apiRequest(`/v1/daily-notes/${encodeURIComponent(date)}/ensure`, "POST", {
          apiVersion: API_VERSION,
          diaryRoot: this.settings.diaryRoot
        });
      }
      async createEvent(event) {
        const data = await this.apiRequest("/v1/events", "POST", {
          apiVersion: API_VERSION,
          event
        });
        return data.event;
      }
      async updateEvent(id, event) {
        const data = await this.apiRequest(`/v1/events/${encodeURIComponent(id)}`, "PUT", {
          apiVersion: API_VERSION,
          event
        });
        return data.event;
      }
      async deleteEvent(id) {
        return this.apiRequest(`/v1/events/${encodeURIComponent(id)}`, "DELETE", {
          apiVersion: API_VERSION
        });
      }
      async openCalendar() {
        const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE)[0];
        const leaf = existing || this.app.workspace.getLeaf(true);
        await leaf.setViewState({ type: VIEW_TYPE, active: true });
        this.app.workspace.revealLeaf(leaf);
      }
      async refreshViews() {
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE)) {
          if (leaf.view && typeof leaf.view.refresh === "function") await leaf.view.refresh();
        }
      }
      dailyNotePath(date) {
        const year = date.slice(0, 4);
        const month = date.slice(0, 7);
        return normalizePath(`${this.settings.diaryRoot}/${year}/${month}/${date}.md`);
      }
      async openDailyNote(date) {
        const path = this.dailyNotePath(date);
        const existing = this.app.vault.getAbstractFileByPath(path);
        if (existing) {
          await this.app.workspace.openLinkText(path, "", false);
          return;
        }
        try {
          const result = await this.ensureDailyNote(date);
          new Notice(result?.created ? `Requested daily note for ${date}.` : `Daily note already exists for ${date}.`);
          await waitForVaultFile(this.app, path, 15e3);
          const created = this.app.vault.getAbstractFileByPath(path);
          if (created) await this.app.workspace.openLinkText(path, "", false);
          else new Notice("The server accepted the request, but Syncthing has not delivered the note yet.");
        } catch (error) {
          new Notice(error.message || String(error));
        }
      }
    };
    var CalendarView = class extends ItemView {
      constructor(leaf, plugin) {
        super(leaf);
        this.plugin = plugin;
        const today = /* @__PURE__ */ new Date();
        this.month = new Date(today.getFullYear(), today.getMonth(), 1);
        this.selectedDate = localDateKey(today);
        this.events = [];
        this.loading = false;
      }
      getViewType() {
        return VIEW_TYPE;
      }
      getDisplayText() {
        return "NAS Calendar";
      }
      getIcon() {
        return "calendar-days";
      }
      async onOpen() {
        await this.refresh();
      }
      async onClose() {
        this.contentEl.empty();
      }
      async refresh() {
        if (!this.contentEl) return;
        this.loading = true;
        this.render();
        try {
          const range = monthRange(this.month);
          this.events = await this.plugin.getEvents(range.start, range.end);
          this.render();
        } catch (error) {
          this.events = [];
          this.render(error.message || String(error));
        } finally {
          this.loading = false;
        }
      }
      render(errorMessage = "") {
        this.contentEl.empty();
        this.contentEl.addClass("nas-calendar-bridge");
        const toolbar = this.contentEl.createDiv({ cls: "nas-calendar-bridge__toolbar" });
        const navigation = toolbar.createDiv({ cls: "nas-calendar-bridge__toolbar-group" });
        button(navigation, "\u2039", "Previous month", () => {
          this.month = new Date(this.month.getFullYear(), this.month.getMonth() - 1, 1);
          this.refresh();
        });
        button(navigation, "Today", "Go to today", () => {
          const today = /* @__PURE__ */ new Date();
          this.month = new Date(today.getFullYear(), today.getMonth(), 1);
          this.selectedDate = localDateKey(today);
          this.refresh();
        });
        button(navigation, "\u203A", "Next month", () => {
          this.month = new Date(this.month.getFullYear(), this.month.getMonth() + 1, 1);
          this.refresh();
        });
        const monthLabel = toolbar.createDiv({ cls: "nas-calendar-bridge__month" });
        monthLabel.setText(this.month.toLocaleDateString(void 0, { month: "long", year: "numeric" }));
        const actions = toolbar.createDiv({ cls: "nas-calendar-bridge__toolbar-group" });
        button(actions, "Refresh", "Refresh events", () => this.refresh());
        button(actions, "+ Event", "Create event", () => {
          new EventModal(this.plugin.app, this.plugin, null, this.selectedDate).open();
        });
        const status = this.contentEl.createDiv({ cls: "nas-calendar-bridge__status" });
        if (this.loading) status.setText("Loading events\u2026");
        if (errorMessage) {
          status.addClass("is-error");
          status.setText(errorMessage);
        }
        const weekdays = this.contentEl.createDiv({ cls: "nas-calendar-bridge__weekdays" });
        const weekdayNames = this.plugin.settings.weekStartsMonday ? ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] : ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
        for (const name of weekdayNames) weekdays.createDiv({ cls: "nas-calendar-bridge__weekday", text: name });
        const grid = this.contentEl.createDiv({ cls: "nas-calendar-bridge__grid" });
        for (const date of calendarDates(this.month, this.plugin.settings.weekStartsMonday)) {
          const dateKey = localDateKey(date);
          const day = grid.createDiv({ cls: "nas-calendar-bridge__day" });
          day.setAttribute("role", "button");
          day.tabIndex = 0;
          day.setAttribute("aria-label", `Open daily note for ${dateKey}`);
          if (date.getMonth() !== this.month.getMonth()) day.addClass("is-outside-month");
          if (dateKey === localDateKey(/* @__PURE__ */ new Date())) day.addClass("is-today");
          if (dateKey === this.selectedDate) day.addClass("is-selected");
          day.addEventListener("click", () => {
            this.selectedDate = dateKey;
            this.plugin.openDailyNote(dateKey);
          });
          day.addEventListener("keydown", (keyboardEvent) => {
            if (keyboardEvent.key === "Enter" || keyboardEvent.key === " ") {
              keyboardEvent.preventDefault();
              this.selectedDate = dateKey;
              this.plugin.openDailyNote(dateKey);
            }
          });
          day.createDiv({ cls: "nas-calendar-bridge__day-number", text: String(date.getDate()) });
          const events = this.events.filter((event) => eventDateKey(event) === dateKey);
          for (const event of events) {
            const eventButton = day.createEl("button", { cls: "nas-calendar-bridge__event" });
            eventButton.type = "button";
            eventButton.style.borderLeftColor = safeColor(event.color);
            eventButton.setAttribute("title", event.description || event.title || "Event");
            eventButton.addEventListener("click", (click) => {
              click.stopPropagation();
              new EventModal(this.plugin.app, this.plugin, event, dateKey).open();
            });
            const time = event.allDay ? "All day" : formatEventTime(event.start);
            eventButton.createSpan({ cls: "nas-calendar-bridge__event-time", text: `${time} ` });
            eventButton.createSpan({ text: event.title || "Untitled event" });
          }
        }
      }
    };
    var EventModal = class extends Modal {
      constructor(app, plugin, event, defaultDate) {
        super(app);
        this.plugin = plugin;
        this.event = event;
        this.defaultDate = defaultDate;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.createEl("h2", { text: this.event ? "Edit event" : "Create event" });
        const start = splitDateTime(this.event?.start, this.defaultDate);
        const end = splitDateTime(this.event?.end, start.date);
        const fields = {};
        fields.title = textSetting(contentEl, "Title", "Event title", this.event?.title || "");
        fields.allDay = checkboxSetting(contentEl, "All day", this.event?.allDay ?? false);
        fields.startDate = textSetting(contentEl, "Start date", "YYYY-MM-DD", start.date);
        fields.startTime = textSetting(contentEl, "Start time", "HH:MM", start.time);
        fields.endDate = textSetting(contentEl, "End date", "YYYY-MM-DD", end.date);
        fields.endTime = textSetting(contentEl, "End time", "HH:MM", end.time);
        fields.topic = textSetting(contentEl, "Topic", "Optional category", this.event?.topic || "");
        fields.color = textSetting(contentEl, "Color", "#7c3aed", this.event?.color || "#7c3aed");
        fields.location = textSetting(contentEl, "Location", "Optional", this.event?.location || "");
        fields.url = textSetting(contentEl, "Link", "https://\u2026", this.event?.url || "");
        fields.recurrence = textSetting(contentEl, "Recurrence", "RRULE:FREQ=WEEKLY (optional)", (this.event?.recurrence || [])[0] || "");
        fields.reminders = textSetting(contentEl, "Email reminders", "Minutes before, comma-separated", (this.event?.reminders || []).filter((reminder) => reminder.method === "email").map((reminder) => reminder.minutesBefore).join(", "));
        fields.attendees = textSetting(contentEl, "Attendees", "Email addresses, comma-separated", (this.event?.attendees || []).join(", "));
        const descriptionSetting = new Setting(contentEl).setName("Description");
        fields.description = descriptionSetting.controlEl.createEl("textarea");
        fields.description.rows = 4;
        fields.description.value = this.event?.description || "";
        fields.description.placeholder = "Optional description";
        const hint = contentEl.createDiv({ cls: "nas-calendar-bridge__form-description" });
        hint.setText("Events are stored by the authenticated NAS calendar backend. Tasks remain Markdown checkboxes.");
        const actions = contentEl.createDiv({ cls: "nas-calendar-bridge__event-actions" });
        if (this.event) {
          button(actions, "Delete", "Delete event", async () => {
            if (!window.confirm("Delete this event from the canonical calendar?")) return;
            try {
              await this.plugin.deleteEvent(this.event.id || this.event.uid);
              this.close();
              new Notice("Event deleted.");
              await this.plugin.refreshViews();
            } catch (error) {
              new Notice(error.message || String(error));
            }
          });
        }
        button(actions, "Cancel", "Cancel", () => this.close());
        button(actions, this.event ? "Save" : "Create", "Save event", async () => {
          const title = fields.title.value.trim();
          if (!title) {
            new Notice("An event title is required.");
            return;
          }
          const allDay = fields.allDay.checked;
          const startDate = fields.startDate.value.trim();
          const endDate = fields.endDate.value.trim() || startDate;
          const startTime = fields.startTime.value.trim() || "09:00";
          const endTime = fields.endTime.value.trim() || "10:00";
          const recurrence = fields.recurrence.value.trim();
          const reminders = fields.reminders.value.split(",").map((value) => Number(value.trim())).filter((value) => Number.isFinite(value) && value >= 0).map((minutesBefore) => ({ method: "email", minutesBefore }));
          const attendees = fields.attendees.value.split(",").map((value) => value.trim()).filter(Boolean);
          const event = {
            title,
            allDay,
            start: allDay ? startDate : `${startDate}T${startTime}`,
            end: allDay ? endDate : `${endDate}T${endTime}`,
            topic: fields.topic.value.trim(),
            color: fields.color.value.trim() || "#7c3aed",
            location: fields.location.value.trim(),
            url: fields.url.value.trim(),
            description: fields.description.value.trim(),
            recurrence: recurrence ? [recurrence] : [],
            reminders,
            attendees
          };
          try {
            if (this.event) await this.plugin.updateEvent(this.event.id || this.event.uid, event);
            else await this.plugin.createEvent(event);
            this.close();
            new Notice(this.event ? "Event updated." : "Event created.");
            await this.plugin.refreshViews();
          } catch (error) {
            new Notice(error.message || String(error));
          }
        });
      }
    };
    var CalendarBridgeSettingsTab = class extends PluginSettingTab {
      constructor(app, plugin) {
        super(app, plugin);
        this.plugin = plugin;
      }
      display() {
        const { containerEl } = this;
        containerEl.empty();
        containerEl.createEl("h2", { text: "NAS Vault settings" });
        containerEl.createEl("p", {
          text: "Use one private NAS base URL. Calendar, vault sync, and enrollment are routed internally by the NAS gateway."
        });
        new Setting(containerEl).setName("NAS base URL").setDesc("Use the private Tailscale address of the NAS, without a service path, credentials, query, or fragment.").addText((text) => text.setPlaceholder("https://nas.example").setValue(this.plugin.settings.nasBaseUrl).onChange(async (value) => {
          this.plugin.settings.nasBaseUrl = migrateNasBaseUrl2(value);
          await this.plugin.saveSettings();
        }));
        new Setting(containerEl).setName("Daily note root").setDesc("Vault-relative folder containing the canonical diary tree.").addText((text) => text.setValue(this.plugin.settings.diaryRoot).onChange(async (value) => {
          this.plugin.settings.diaryRoot = value.trim() || DEFAULT_SETTINGS.diaryRoot;
          await this.plugin.saveSettings();
        }));
        new Setting(containerEl).setName("Week starts on Monday").addToggle((toggle) => toggle.setValue(this.plugin.settings.weekStartsMonday).onChange(async (value) => {
          this.plugin.settings.weekStartsMonday = value;
          await this.plugin.saveSettings();
        }));
        new Setting(containerEl).setName("Device name").setDesc("Shown only to this account. Active device names must be unique within the account.").addText((text) => text.setPlaceholder("Phone").setValue(this.plugin.settings.syncDeviceName).onChange(async (value) => {
          this.plugin.settings.syncDeviceName = value.trim();
          await this.plugin.saveSettings();
        }));
        new Setting(containerEl).setName("Connect to NAS").setDesc("Register a new account or sign in and connect this device. The NAS stores its credential locally.").addButton((button2) => button2.setButtonText("Connect to NAS").onClick(() => this.plugin.connectViaMultiUserEnrollment()));
        new Setting(containerEl).setName("Your active devices").setDesc("Shows devices currently authorized for this account. Devices unseen for 30 days are removed automatically.").addButton((button2) => button2.setButtonText("Manage devices").onClick(() => new DeviceManagerModal(this.app, this.plugin).open()));
        new Setting(containerEl).setName("Initial sync after connecting").setDesc("After a new device connects, asks whether to import this vault into the account or begin from the account's server vault.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoInitialSyncAfterPairing !== false).onChange(async (value) => {
          this.plugin.settings.autoInitialSyncAfterPairing = value;
          await this.plugin.saveSettings();
        }));
        new Setting(containerEl).setName("Automatic vault sync").setDesc("Checks and syncs when Obsidian opens or resumes, and after local changes. Enable only after Syncthing is stopped for this vault.").addToggle((toggle) => toggle.setValue(this.plugin.settings.automaticVaultSync).onChange(async (value) => {
          this.plugin.settings.automaticVaultSync = value;
          await this.plugin.saveSettings();
          this.plugin.startVaultSyncPolling();
        }));
        new Setting(containerEl).setName("Automatic sync poll interval (seconds)").setDesc("Checks the NAS for remote changes while Obsidian is open. Minimum 10 seconds; mobile background execution is not guaranteed.").addText((text) => {
          text.inputEl.type = "number";
          text.setValue(String(this.plugin.settings.automaticVaultSyncIntervalSeconds || 30));
          text.onChange(async (value) => {
            const seconds = Math.max(10, Math.min(3600, Number(value) || 30));
            this.plugin.settings.automaticVaultSyncIntervalSeconds = seconds;
            text.setValue(String(seconds));
            await this.plugin.saveSettings();
            this.plugin.startVaultSyncPolling();
          });
        });
        new Setting(containerEl).setName("Sync vault now").setDesc("Runs a manual three-way synchronization after the first-sync baseline has been established.").addButton((button2) => button2.setButtonText("Sync now").onClick(() => this.plugin.syncVaultNow()));
        new Setting(containerEl).setName("Check NAS connection").setDesc("Checks calendar and vault-sync access without transferring or changing data.").addButton((buttonEl) => buttonEl.setButtonText("Check connection").onClick(() => this.plugin.checkNasConnection()));
      }
    };
    var DeviceManagerModal = class extends Modal {
      constructor(app, plugin) {
        super(app);
        this.plugin = plugin;
      }
      async onOpen() {
        await this.refresh();
      }
      async refresh() {
        const el = this.contentEl;
        el.empty();
        el.createEl("h2", { text: "Your active devices" });
        const status = el.createEl("p", { text: "Loading devices\u2026" });
        try {
          const value = await this.plugin.activeDevices();
          const devices = Array.isArray(value?.devices) ? value.devices : [];
          status.setText(devices.length ? "These devices can currently access this account." : "No active devices are registered.");
          for (const device of devices) {
            if (!device || typeof device.name !== "string") continue;
            const row = new Setting(el).setName(device.name).setDesc(formatLastSeen(device.lastSeenAt));
            row.addButton((buttonEl) => buttonEl.setButtonText("Revoke").setWarning().onClick(async () => {
              if (!window.confirm(`Revoke ${device.name}? Its access will stop immediately; account content is not deleted.`)) return;
              await this.plugin.revokeActiveDevice(device.name);
              if (device.name === this.plugin.settings.syncDeviceName) this.plugin.setDeviceCredential("");
              await this.refresh();
            }));
          }
        } catch (error) {
          status.setText(error.message || "Could not load devices.");
        }
      }
      onClose() {
        this.contentEl.empty();
      }
    };
    var PortalEnrollmentModal = class extends Modal {
      constructor(app, plugin, portal, pairing) {
        super(app);
        this.plugin = plugin;
        this.portal = portal;
        this.pairing = pairing;
        this.timer = null;
        this.pollInFlight = false;
      }
      onOpen() {
        const el = this.contentEl;
        el.empty();
        el.createEl("h2", { text: "Continue in NAS Vault" });
        el.createEl("p", { text: "The private NAS page lets you sign in or register. It will authorize this device after email verification; the device credential is never displayed." });
        const status = el.createEl("p", { text: "Opening the private NAS page\u2026" });
        const open = el.createEl("button", { text: "Open NAS Vault" });
        open.addEventListener("click", () => this.openPortal());
        this.openPortal();
        this.timer = window.setInterval(async () => {
          if (this.pollInFlight) return;
          this.pollInFlight = true;
          try {
            const value = await enrollmentRequest(this.portal, `/api/v2/pairing/poll?token=${encodeURIComponent(this.pairing.pollToken)}`);
            if (value.status === "complete") {
              window.clearInterval(this.timer);
              if (value.apiVersion !== 2 || typeof value.token !== "string") throw new Error("Enrollment portal returned an incompatible response.");
              this.plugin.setDeviceCredential(value.token);
              this.plugin.settings.initialSyncCompleted = false;
              await this.plugin.saveSettings();
              if (this.plugin.settings.autoInitialSyncAfterPairing !== false && !loadSyncState2(this.plugin.syncStateScope())) {
                status.setText("Device connected. Choose how to establish the first vault baseline\u2026");
                const result = await this.plugin.chooseInitialSync();
                if (result) {
                  status.setText(`Device connected and initial sync complete (${result.downloaded} downloaded, ${result.conflicts} conflicts preserved).`);
                  new Notice("NAS device connection and initial vault sync complete.");
                } else status.setText("Device connected, but the initial sync did not complete. Run Sync vault now to retry.");
              } else {
                status.setText("Device connected. You can close this window.");
                new Notice("NAS device connection complete.");
              }
            }
          } catch (error) {
            window.clearInterval(this.timer);
            status.setText(error.message || String(error));
          } finally {
            this.pollInFlight = false;
          }
        }, 2500);
      }
      openPortal() {
        const url = new URL(this.portal);
        if (!url.pathname.endsWith("/")) url.pathname += "/";
        url.searchParams.set("pairing", this.pairing.pairingCode);
        window.open(url.toString(), "_blank", "noopener,noreferrer");
      }
      onClose() {
        if (this.timer) window.clearInterval(this.timer);
        this.contentEl.empty();
      }
    };
    async function loadLegacySettings(app) {
      const adapter = app?.vault?.adapter;
      if (!adapter || typeof adapter.read !== "function") return void 0;
      try {
        const configDir = app.vault.configDir || ".obsidian";
        const path = normalizePath(configDir + "/plugins/" + LEGACY_PLUGIN_ID + "/data.json");
        const value = JSON.parse(await adapter.read(path));
        return value && typeof value === "object" && !Array.isArray(value) ? value : void 0;
      } catch (_error) {
        return void 0;
      }
    }
    function migrateSettings(value) {
      const settings = Object.assign({}, DEFAULT_SETTINGS, value || {});
      settings.nasBaseUrl = migrateNasBaseUrl2(settings.nasBaseUrl, value || {});
      delete settings.apiBaseUrl;
      delete settings.syncApiBaseUrl;
      delete settings.enrollmentPortalUrl;
      delete settings.calendarId;
      return settings;
    }
    function localVaultScope(app) {
      const value = String(app?.vault?.adapter?.basePath || app?.vault?.getName?.() || "default");
      let hash = 2166136261;
      for (let index = 0; index < value.length; index += 1) {
        hash ^= value.charCodeAt(index);
        hash = Math.imul(hash, 16777619);
      }
      return (hash >>> 0).toString(36);
    }
    function localStateHash(value) {
      let hash = 2166136261;
      for (let index = 0; index < value.length; index += 1) {
        hash ^= value.charCodeAt(index);
        hash = Math.imul(hash, 16777619);
      }
      return (hash >>> 0).toString(36);
    }
    function formatLastSeen(value) {
      if (!Number.isInteger(value) || value <= 0) return "Last contact is unavailable.";
      return `Last online ${new Date(value * 1e3).toLocaleString()}.`;
    }
    async function enrollmentRequest(base, path, method = "GET", body = void 0, credential = "") {
      let url;
      try {
        const parsed = new URL(base.trim());
        if (!/^https?:$/.test(parsed.protocol) || parsed.username || parsed.password || parsed.search || parsed.hash) throw new Error();
        url = base.trim().replace(/\/$/, "") + path;
      } catch (_error) {
        throw new Error("Configure a valid private NAS base URL.");
      }
      const response = await requestUrl({
        url,
        method,
        headers: { Accept: "application/json", ...body === void 0 ? {} : { "Content-Type": "application/json" }, ...credential ? { Authorization: `Bearer ${credential}` } : {} },
        body: body === void 0 ? void 0 : JSON.stringify(body),
        throw: false
      });
      let value;
      try {
        value = JSON.parse(response.text);
      } catch (_error) {
        throw new Error("Enrollment portal returned an invalid response.");
      }
      if (response.status < 200 || response.status >= 300) throw new Error(value.message || `Enrollment failed (HTTP ${response.status}).`);
      return value;
    }
    function textSetting(parent, name, placeholder, value) {
      const setting = new Setting(parent).setName(name);
      const input = setting.controlEl.createEl("input");
      input.type = "text";
      input.placeholder = placeholder;
      input.value = value;
      return input;
    }
    function checkboxSetting(parent, name, value) {
      const setting = new Setting(parent).setName(name);
      const input = setting.controlEl.createEl("input");
      input.type = "checkbox";
      input.checked = value;
      return input;
    }
    function button(parent, label, ariaLabel, onClick) {
      const element = parent.createEl("button", { text: label });
      element.type = "button";
      element.setAttribute("aria-label", ariaLabel);
      element.addEventListener("click", onClick);
      return element;
    }
    function localDateKey(date) {
      const year = String(date.getFullYear()).padStart(4, "0");
      const month = String(date.getMonth() + 1).padStart(2, "0");
      const day = String(date.getDate()).padStart(2, "0");
      return `${year}-${month}-${day}`;
    }
    function calendarDates(month, mondayFirst) {
      const first = new Date(month.getFullYear(), month.getMonth(), 1);
      const last = new Date(month.getFullYear(), month.getMonth() + 1, 0);
      const firstDay = mondayFirst ? (first.getDay() + 6) % 7 : first.getDay();
      const total = Math.ceil((firstDay + last.getDate()) / 7) * 7;
      const start = new Date(first);
      start.setDate(first.getDate() - firstDay);
      return Array.from({ length: total }, (_unused, index) => {
        const date = new Date(start);
        date.setDate(start.getDate() + index);
        return date;
      });
    }
    function monthRange(month) {
      const start = new Date(month.getFullYear(), month.getMonth(), 1);
      const end = new Date(month.getFullYear(), month.getMonth() + 1, 1);
      return { start: localDateKey(start), end: localDateKey(end) };
    }
    function eventDateKey(event) {
      if (!event || typeof event.start !== "string") return "";
      if (/^[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(event.start)) return event.start.slice(0, 10);
      return localDateKey(new Date(event.start));
    }
    function formatEventTime(value) {
      if (!value) return "";
      const date = new Date(value);
      if (Number.isNaN(date.getTime())) return value.slice(11, 16) || value;
      return date.toLocaleTimeString(void 0, { hour: "2-digit", minute: "2-digit" });
    }
    function splitDateTime(value, fallbackDate) {
      if (typeof value === "string" && /^[0-9]{4}-[0-9]{2}-[0-9]{2}/.test(value)) {
        return { date: value.slice(0, 10), time: value.length >= 16 ? value.slice(11, 16) : "09:00" };
      }
      return { date: fallbackDate, time: "09:00" };
    }
    function safeColor(value) {
      if (typeof value !== "string") return "var(--interactive-accent)";
      if (/^#[0-9a-f]{3,8}$/i.test(value)) return value;
      if (/^rgba?\([0-9., %]+\)$/.test(value)) return value;
      return "var(--interactive-accent)";
    }
    async function waitForVaultFile(app, path, timeoutMs) {
      const started = Date.now();
      while (Date.now() - started < timeoutMs) {
        if (app.vault.getAbstractFileByPath(path)) return true;
        await new Promise((resolve) => window.setTimeout(resolve, 500));
      }
      return false;
    }
    module2.exports = NasCalendarBridge;
  }
});

// src/main.ts
var CalendarPlugin = require_calendar();
module.exports = CalendarPlugin;
